import koreanGrandma from "../../assets/ArticlePics/queenElizabeth.jpg"

function homeHalmoni(){
    return(
    <div>
            <figure class="image is-256x128" width="100%" height="100%">
                <img src={koreanGrandma} alt="Failed to Load" width="100%" height="100%"/>
                <p style={{fontSize:'x-small'}}>
                  AI Art generated by MidJourney
                </p>
              </figure>

              <div class="card-body">
                <a href="/halmoni" style={{textDecoration: 'none'}}>
                  <h5 class="card-text" style={{textDecoration: 'underline', color: 'black'}}>Halmoni and Me </h5>
                </a>
              </div>

              <div style={{textAlign: 'right'}}>
                <p class="text-muted py-2" style={{textAlign:'right'}}>
                  By: Jessica Tadokoro
                </p>
              </div>
    </div>
    );

}

export default homeHalmoni;