// article images
import koreanGrandma from "../assets/ProsePics/koreanGrandma.png"
import mulan from "../assets/ArticlePics/mulan.png"
import liliuokalani from "../assets/ArticlePics/liliuokalani.png"
import eeaaooscar from "../assets/ArticlePics/eeaao.png"
import olivia from "../assets/ArticlePics/olivia.png"
import flight from "../assets/ProsePics/Flight.jpg"
import grace from "../assets/ArticlePics/grace.jpg"

//divisions: 
// plushy prose
// expectations end article piece
import mentalHealth from "../assets/ArticlePics/mentalHealth.jpg"
import plushy from "../assets/ArticlePics/plushy.png"
import parentalExpectations from "../assets/ArticlePics/parentalExpectations.jpg"
import dating from "../assets/ArticlePics/dating.jpg"
import boba from "../assets/ArticlePics/boba.jpg"

// components
import homeTemplate from "../components/homeComponents/homeCard.jsx"
import "../css/globalComponents.css"

const TITLE = 'DAY USC';

function Home() {
  return (
    <div>
    <title>{ TITLE }</title>
    <div class="py-3">
      <div class="container-fluid" style={{'max-width':'90%'}}>
        <div class="row">

          <div class="col" style={{borderRight: '1px solid black'}}>
          <h2 style={{textAlign:'right', fontStyle:'italic', border:'bold'}}> Creative</h2>
            <div>
              {homeTemplate(plushy, "Rilakkuma designed by Aki Kondo", "/plushy", "Ode to Plushy", 
              "Joseph Caluya")}

              {homeTemplate(dating, "", "/utahboys", "Reasons Why I Won't Date White Boys from Utah Anymore", 
              "Katie Sanyal")}

              <h3 style={{textAlign:'right', color:'black', fontStyle:'italic', fontWeight:'bold'}}>Prose</h3>
              {homeTemplate(flight, "", "/flight", "The Flight", "Andrew Kim")}

              {homeTemplate(parentalExpectations, "", "/expectations", "Family Expectations Growing Up", 
              "Sydney Fiorentino")}

              {homeTemplate(koreanGrandma, "AI Art generated by Midjourney", "/halmoni", "Halmoni and Me", 
              "Jessica Tadokoro")}

              

            </div>
          </div>

          <div class="col-6" style={{borderRight: '1px solid black'}}>
          <h2 style={{textAlign:'right', fontStyle:'italic', border:'bold'}}> Featured</h2>
            <div>
              {homeTemplate(olivia, "", "/aaab", 
              "All (Asian)-American Bitch", "Yi-Ann Li")}

              <div class="py-1">
              </div>

              {homeTemplate(mentalHealth, "Illustrated by Laura Whelan", "/lolsorry", 
              "lol sorry i’m being depressing: destigmatizing mental illness in the asian-american community",
              "Ina Ycasas")}

              {homeTemplate(eeaaooscar, "", "/eeaao",
              "Why Everything Everywhere All at Once Winning 7 Oscars is Significant", "Jeen Lee")}

            </div>
          </div>

          <div class="col" width="25%">
            <h2 style={{textAlign:'right', fontStyle:'italic', border:'bold'}}> News</h2>
              {homeTemplate(mulan, "", "/comfortfilms", "Animated APIDA Comfort Films", "Ina Ycasas")}

              {homeTemplate(liliuokalani, "", "/apidawomen", 
              "Notable APIDA Women to Spotlight During Women's History Month", "Jeen Lee")}

              {homeTemplate(grace, "", "/grace", "Grace Young: From 'Stir-fry Guru' to 'Woman of the Year'", 
              "Celine Chen")}

              {homeTemplate(boba, "Photographer: Francisco Cordosa", "/reflections", "Reflections", 
              "Patrick Fang")}
          </div>
        </div>
      </div>
      </div>
    </div>
  );
}

export default Home;