// article images
import koreanGrandma from "../assets/ProsePics/koreanGrandma.png"
import mulan from "../assets/ArticlePics/mulan.png"
import liliuokalani from "../assets/ArticlePics/liliuokalani.png"
import eeaaooscar from "../assets/ArticlePics/eeaao.png"
import olivia from "../assets/ArticlePics/olivia.png"

// art
import ophelia from "../assets/Art/EthanZhang/Ophelia_painting.jpg"
import girlSketch from "../assets/Art/EthanZhang/girl_long_hair_sketch.jpg"
import tiger from "../assets/Art/HelenaYu/helenaArt.jpg"

// components
import homeTemplate from "../components/homeComponents/homeCard.jsx"
import "../css/globalComponents.css"

const TITLE = 'DAY USC';

function Home() {
  return (
    <div>
    <title>{ TITLE }</title>
    <div class="py-3">
      <div class="container-fluid" style={{'max-width':'90%'}}>
        <div class="row">

          <div class="col" style={{borderRight: '1px solid black'}}>
            <div>
              {homeTemplate(mulan, "", "/comfortfilms", "Animated APIDA Comfort Films", "Ina Ycasas")}
              {homeTemplate(liliuokalani, "", "/apidawomen", "Notable APIDA Women to Spotlight During Women's History Month", "Jeen Lee")}

              <h3 style={{color:'black', fontWeight:'bold'}}>Prose</h3>
              {homeTemplate(koreanGrandma, "AI Art generated by Midjourney", "/halmoni", "Halmoni and Me", "Jessica Tadokoro", "FAMILY & HERITAGE")}

            </div>
          </div>

          <div class="col-6" style={{borderRight: '1px solid black'}}>
            <div>
              {homeTemplate(olivia, "", "/aaab", 
              "All (Asian)-American Bitch", "Yi-Ann Li")}

              <div class="py-1">
              </div>

              {homeTemplate(eeaaooscar, "", "/eeaao",
              "Why Everything Everywhere All at Once Winning 7 Oscars is Significant", "Jeen Lee")}
            </div>
          </div>

          <div class="col" width="25%">
            <h2 style={{textAlign:'right', fontStyle:'italic', border:'bold'}}> News</h2>
              {homeTemplate(ophelia, "", "", "Ophelia", "Ethan Zhang")}
              {homeTemplate(girlSketch, "", "", "Sketch", "Ethan Zhang")}
              {homeTemplate(tiger, "", "", "Nian", "Helena Yu")}
          </div>
        </div>
      </div>
      </div>
    </div>
  );
}

export default Home;