// article images
import koreanGrandma from "../assets/ProsePics/koreanGrandma.png"
import mulan from "../assets/ArticlePics/mulan.png"
import eeaaooscar from "../assets/ArticlePics/eeaao.png"
import olivia from "../assets/ArticlePics/olivia.png"
import flight from "../assets/ProsePics/Flight.jpg"
import grace from "../assets/ArticlePics/grace.jpg"

//divisions: 
// plushy prose
// expectations end article piece
import mentalHealth from "../assets/ArticlePics/mentalHealth.jpg"
import plushy from "../assets/ArticlePics/plushy.png"
import parentalExpectations from "../assets/ArticlePics/parentalExpectations.jpg"
import dating from "../assets/ArticlePics/dating.jpg"
import boba from "../assets/ArticlePics/boba.jpg"

// components
import homeTemplate from "../components/homeComponents/homeCard.jsx"
import newsColumn from "../components/homeComponents/newsColumn.jsx"
import "../css/globalComponents.css"

const TITLE = 'DAY USC';

function Home() {
  return (
    <div>
    <title>{ TITLE }</title>
    <div class="py-3">
      <div class="container-fluid" style={{'max-width':'90%'}}>
        <div class="row">

          <div class="col" style={{borderRight: '1px solid black'}}>
          <div>
          <h2 class="newsColumn"> Creative</h2>

              {homeTemplate(flight, "", "/flight", "The Flight", "PROSE", "Story highlighting a familiar feeling Asian-Americans share: the disconnect between one and their mother country's language.", "Andrew Kim")}
              {homeTemplate(koreanGrandma, "AI Art generated by Midjourney", "/halmoni", "Halmoni and Me", "POETRY", "A poem that shows how familial love overcomes even the toughest of obstacles.", "Jessica Tadokoro")}
            
              {homeTemplate(plushy, "Rilakkuma designed by Aki Kondo", "/plushy", "Ode to Plushy", "POETRY", "Written for the seemingly insignificant things that actually save us when we need it most.",
              "Joseph Caluya")}

              {homeTemplate(dating, "", "/utahboys", "Reasons Why I Won't Date White Boys from Utah Anymore", "POETRY", "Poem that defies negative stereotypes about people with mixed ethnicities.", 
              "Katie Sanyal")}

              {homeTemplate(parentalExpectations, "", "/expectations", "Family Expectations Growing Up", "PROSE", "Details the relatable pressures of growing up in an Asian-American household.",
              "Sydney Fiorentino")}

            </div>
          </div>

          <div class="col-6" style={{borderRight: '1px solid black'}}>
          <div>
              {homeTemplate(olivia, "", "/aaab", 
              "All (Asian)-American Bitch", "ENTERTAINMENT/OPINION", "How Olivia Rodrigo's new song reclaims & challenges boxes surrounding the identity of the Asian-American woman.", "Yi-Ann Li")}

              <div class="py-1">
              </div>

              {homeTemplate(mentalHealth, "Illustrated by Laura Whelan", "/lolsorry", 
              "lol sorry i’m being depressing: destigmatizing mental illness in the asian-american community", "SOCIETAL ISSUES",
              "Addressing an important topic that isn't often talked about in the Asian community.", "Ina Ycasas")}

              {homeTemplate(eeaaooscar, "", "/eeaao",
              "Why Everything Everywhere All at Once Winning 7 Oscars is Significant", "ENTERTAINMENT", "How this movie represents a win for Asians in an industry that lacks Asian representation.", "Jeen Lee")}
            </div>
          </div>

          <div class="col" width="25%">
            {newsColumn()}
          </div>
        </div>
      </div>
      </div>
    </div>
  );
}

export default Home;