import queen from "../assets/ArticlePics/queenElizabeth.jpg"
import monterey from "../assets/ArticlePics/MontereyPic.jpg"
import kimSejeong from "../assets/ArticlePics/kimSejeong.jpg"
import fashionPic from "../assets/ArticlePics/fashionPic.jpg"
import koreanGrandma from "../assets/ProsePics/koreanGrandma.png"

import LiteratureContainer from "../components/litComponents/litContainer.jsx"
import HalmoniContainer from "../components/litComponents/halmoniComponent.jsx"

const queenTitle = "The Crown Jewels and Colonialism";
const queenAuthor = "By: Bridget Zhang";
const queenExcerpt = "Queen Elizabeth II died on September 8, 2022, marking the end of a 70-year reign. As a symbol of the British monarchy, her legacy cannot be separated from that of the colonial empire. This is seen most obviously through the precious stones that she wore, many of which were taken from former colonies. Since her death, there have been renewed calls for the jewels to be returned to their rightful owners.";
const queenImageCredit = "Bettmann Archive/Getty Images";
const queenPage = "/colonialism";

const fashionTitle = "South Asian New York Fashion Week 2022";
const fashionAuthor = "By: Jeen Lee";
const fashionExcerpt = "Ever since its launch in 1943, New York Fashion Week has evolved to keep up with the changing demands of its consumers. The latest change has been the official launch of the South Asian New York Fashion Week (SANYFW) to uplift fashion inspired by both traditional and modern South Asian cultures.";
const fashionImageCredit = "ARIF ALI/AFP VIA GETTY IMAGES";
const fashionPage = "/fashion";

const shootingTitle = "Mass Shooting in Monterey Park on Lunar New Year's Eve";
const shootingAuthor = "By: Yi-Ann";
const shootingExcerpt = "On a night meant to be full of joy and ushering in luck and fortune, Lunar New Year festivities in Monterey Park faced a devastating tragedy. According to the Los Angeles Police Department, a gunman opened fire on Saturday night and killed ten people, wounding ten more. As of now, details about the shooter are limited and not public. The gunman is still at large, and the second day of the Lunar New Year festival in Monterey Park has been canceled.";
const shootingImageCredit = "Photographer: Jae C. Hong/AP";
const shootingPage = "/monterey";

const kpopTitle = "A Re-Cap of USC'S K-Pop Festa";
const kpopAuthor = "By: Joseph Caluya";
const kpopExcerpt = "Korean culture has become more ubiquitous in the past few years as an ever-increasing number of people watch K-dramas, listen to K-Pop, eat Korean food, and add K-beauty products to their routines. This growth has been further demonstrated with the rise of K-culture events such as the K-Pop Festa at McCarthy Quad on Sep. 23, 2022, in which USC became the first campus in America to ever host a K-Pop concert.";
const kpopPage = "/kpop";

const halmoniTitle = "Halmoni and Me";
const halmoniAuthor = "By: Jessica Tadokoro";
const halmoniImageCredit = "AI Art generated by MidJourney";
const halmoniPage = "/halmoni";

function Literature()
{
    return(
        <>
        <div id="container">
            
            <h2 class="py-4" style={{textAlign:'center', textDecoration: 'underline', color: 'red'}}><b>News Articles</b></h2>

            <div class="py-2"></div>

            <div class="row">
                {LiteratureContainer(queenTitle, queenAuthor, queenExcerpt, queen, queenImageCredit, queenPage)}
            </div>

            <div class="py-4"></div>

            <div class="row">
                {LiteratureContainer(fashionTitle, fashionAuthor, fashionExcerpt, fashionPic, fashionImageCredit, fashionPage)}
            </div>

            <div class="py-4"></div>

            <div class="row">
                {LiteratureContainer(shootingTitle, shootingAuthor, shootingExcerpt, monterey, shootingImageCredit, shootingPage)}
            </div>

            <div class="py-4"></div>

            <div class="row">
                {LiteratureContainer(kpopTitle, kpopAuthor, kpopExcerpt, kimSejeong, "", kpopPage)}
            </div>

            <div class="py-4"></div>

            <hr></hr>

            <div class="py-2"></div>

            <div class="row">
                <h2 class="py-4" style={{textAlign:'center', textDecoration: 'underline', color: 'red'}}><b>Prose</b></h2>
            </div>
            
            <div class="py-4"></div>

            <div class="row">
                {HalmoniContainer(halmoniTitle, halmoniAuthor, koreanGrandma, halmoniImageCredit, halmoniPage)}
            </div>

        </div>
        </>
    );
}
export default Literature;