import plushy from "../assets/ArticlePics/plushy.png"
import titleTemplate from "../components/articleComponents/titleTemplate"
import quotesTemplate from "../components/articleComponents/quotesTemplate"
import bodyTemplate from "../components/articleComponents/bodyTemplate"

//JOSEPH REFORMAT THIS IF YOU WANT
const category = "POETRY";
const title = "Ode to Plushy";
const author = "BY: JOSEPH CALUYA";
const date = "MAY 2, 2023";
const stanza1 = ["(dark endless voids with shimmering glints of bliss), \nmeander through the velvety tufts of fur, \nthe welcoming smile (like you didn’t know what pain was),\nthe open arms waiting to reel me in \n for a hug I’ve been needing for who knows how long."]
const stanza2 = ["They call you worthless,\nCall me childish,\nCall us both worthless and childish.\nWords incise like piercing daggers from their eyes,\nBut we both know\nYou and I\nHave a bond tighter than the snout\nSewed onto you.\nYou are a brown, chubby, gentle cushion of love,\nI am a brown, chubby, gentle cushion of love–\nAnd lonely.\nWe pair well like that."]
const stanza3 = ["When I couldn’t see anything except my nebulous fog of failure,\nCouldn’t feel anything except numbness and the nothingness of my existence,\nCouldn’t taste anything except the bitter punch of defeat,\nYou enveloped me with a new sense of tangibility;\nI felt present, felt grounded, felt human.\nLike I was specifically made for the earth,\nLike my eyes were made to be blissful oceans people basked in,\nLike my smile was made to make people forget the feeling of agony,\nLike my arms were made to grasp that one person clinging on the edge of a cliff atop death."]
const stanza4 = ["So I stitched together all the bits and pieces,\nWove tightly all the memories of light and laughter\nAnd loathing and living and leaving\nAnd lament and grieving\nAnd made a smile of my own.\nAnd it was soft, delicate, mellow."]

const quotes1 = ["My eyes fixate on yours–"]
const quotes2 = ["And slightly broken."]
const quotes3 = ["Like yours."]

function Plushy()
{
    return(
            <div class="container">
                <div class="row justify-content-center">

                    <div class="col-10">
                        {titleTemplate(category, title, author, date)}

                        <div class="article-image">
                            <img src={plushy}/>
                            <p class={"imgcred"}>Generated by DALLE</p>
                        </div>
                    </div>
                    <div class="col-6">
                        {quotesTemplate(quotes1)}
                        {bodyTemplate(stanza1)}
                        {bodyTemplate(stanza2)}
                        {bodyTemplate(stanza3)}
                        {bodyTemplate(stanza4)}
                        {quotesTemplate(quotes2)}
                        {quotesTemplate(quotes3)}

                    </div>

                </div>
            </div>
        
    );

}
export default Plushy;