/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://bjizstexznaude5r6jmmbgedfy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-am4ysuv7njcsvfiu6xn3asf4ny",
    "aws_user_files_s3_bucket": "daywebsitereact-storage-4bc14e8991458-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_a": "da2-dtryfpclrjb3rnknbbib47a5u4"
};


export default awsmobile;
