/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://252t3cl6yffvrpsdj5d466qygq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dtryfpclrjb3rnknbbib47a5u4",
    "aws_cognito_identity_pool_id": "us-east-1:bf616e65-d8ef-48b0-a6e8-1cafb48417f9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_L4qeDeFdc",
    "aws_user_pools_web_client_id": "48ptsgmibfu2emdftdmsrlunu8",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "GIVEN_NAME",
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "daywebsitereact-storage-4bc14e89184229-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
